#!/usr/bin/env python3

import nltk
import os
import cs50
import helpers
import sys
from analyzer import Analyzer
from termcolor import colored


def main():
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
        
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    analyzer = Analyzer(positives, negatives)
    
    tweets = helpers.get_user_timeline((sys.argv[1].strip('@')), 50) #get 50 most recent tweets
    
    if tweets == None: #moving after tweets is initialized
        sys.exit("Private or nonexistant account")
        
    
    for tweet in tweets:
        value = analyzer.analyze(tweet)
        if  value > 0.0:
            print(colored("{} {}".format(value, tweet), "green"))
        elif value < 0.0:
            print(colored("{} {}".format(value, tweet), "red"))
        else:
            print(colored("{} {}".format(value, tweet), "yellow"))

if __name__ == "__main__":
    main()

